#!/bin/bash

function main {
  # Exit 0 if CI.
  if [ -n "$CI" ]; then
    exit 0
  fi

  # Install mise If not found.
  local mise=~/.local/bin/mise
  if [ ! -f "$mise" ]; then
    curl https://mise.run | sh
  fi

  # Activate
  eval "$($mise activate zsh)"
  # To load antidote
  source "$HOME/.config/antidote/antidoterc"
  # To trigger remote chezmoi update
  mise run 'config:*'
}

main
