#!/bin/bash

function main {

  # If the variable CI not found.
  if [ -z "$CI" ]; then

    # Install mise If not found.
    local mise=~/.local/bin/mise
    if [ ! -f "$mise" ]; then
      curl https://mise.run | sh
    fi

    # Activate
    eval "$($mise activate zsh)"
  fi

  # To trigger remote chezmoi update
  ~/.local/bin/mise run 'config:*' || ture
}

main
