[tools]
github-cli = "2.74.0"
ruby = { version = "2.6.10", postinstall = 'gem update --system 3.2.3' }
"gem:bundler" = "2.4.22"
"gem:digest-crc" = "0.7.0"
"gem:json" = "2.7.6"
"gem:nkf" = "0.2.0"
"gem:sysrandom" = "1.0.5"
"gem:unf" = "0.2.0"

[settings]
experimental = true

[hooks]
postinstall = "mise run"

[env]
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"
