[tasks.default]
description = "Run all build tasks"
run = '''
'''

[env]
# [doc] https://github.com/jdx/mise/blob/86520c50c267fa6844326da70355534e46e043f8/docs/configuration.md?plain=1#L380
MISE_RAW = 1

[tasks."build:antidote"]
description = "Clone the cure to slow zsh plugin management"
hide = true
sources = ["$HOME/.local/share/antidote"]
outputs = { auto = true }
run = '''
	# Running...
	antidote_dir="$HOME/.local/share/antidote"
	rm -rf "$antidote_dir"
	git clone --quiet --depth=1 https://github.com/mattmc3/antidote.git "$antidote_dir"
'''

[tasks."config:dotfiles"]
description = "Update the dotfiles via chezmoi"
hide = true
tools.chezmoi = "latest"
env.GITHUB_USERNAME = "rick-c-137-137"
run = '''
	# Running...
	lock_dir="$HOME/.chezmoi.lock"
	if mkdir "$lock_dir" 2>/dev/null; then
  	  trap 'rm -rf "$lock_dir"; echo "Lock released."' EXIT

  	  echo "Running task..."
	  if ! chezmoi source-path >/dev/null 2>&1; then
	    echo chezmoi init --apply $GITHUB_USERNAME;
	  else
	    echo chezmoi update --force
	  fi
	fi
'''

[tasks."config:macos"]
description = "Update macOS config"
hide = true
run = '''
	# Running...
	defaults write -g com.apple.mouse.scaling 20
'''

[tasks."config:global-dot-gitconfig"]
description = "Make the dotfiles"
hide = true
sources = ["$HOME/.gitconfig"]
outputs = { auto = true }
run = '''
	# Running...
	git config --global push.autoSetupRemote true
	git config --global pager.branch false
	git config --global credential.helper ""
'''

[tasks."restart:macos"]
description = "Restart macOS"
hide = true
run = '''
	#!/bin/bash
	rm -rf .zsh_sessions
	killall Runner\.Listener
	sleep 3 & exit \
	& osascript -e 'tell application "Terminal" to set mainID to id of front window' \
		-e 'tell application "Terminal" to close (every window whose id ≠ mainID) without saving' \
	& osascript -e 'tell app "System Events" to restart' \
	& echo "$(date): Restart mac successfully"  >> "$HOME/Desktop/log_restart_mac.txt"
'''




