[tools]
"gem:bundler" = "2.4.22"
github-cli = "2.74.0"
ruby = "2.6.10"

[settings]
experimental = true

[hooks]
postinstall = "mise run"

[env]
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"

[tasks.default]
run = """
# Checking RubyGems version.
#!/bin/bas
if [ "$(gem -v)" != "3.2.3" ]; then
  gem update --system 3.2.3
fi
"""